language: node_js

os:
  - linux
  - windows
  - osx

cache:
  timeout: 60
  npm: true
  yarn: true
  directories:
    - node_modules/ # npm packages
    - .nyc_output/

node_js:
  - 'node'
  - lts/*
  - '10'

before_install:
  - npm install yarn -g --registry https://registry.npmjs.org/
  - npm install codecov -g --registry https://registry.npmjs.org/

install:
  - yarn --ignore-engines --registry https://registry.npmjs.org/

script:
  - yarn coverage

stages:
  - test
  - name: compile
  - name: deploy
    if: brance = master

jobs:
  include:
    - stage: lint
      name: "eslint"
      script: yarn lint
    - stage: test
      name: "Unit Tests"
      script: yarn coverage
      after_success:
        - codecov -f .nyc_output/*.json
    - stage: compile
      branches: master
      script: yarn build
      after_success:
        - codecov -f .nyc_output/*.json
    - stage: deploy
      provider: npm
      email: $NPM_MAIL
      script: skip
      branches: master
