language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

install:
  - npm install

script:
  - npm install codecov -g
  - npm test
  - codecov -f coverage/*.json

