language: node_js

os:
  - linux
  - windows
  - osx

cache:
  timeout: 60
  npm: true
  yarn: true
  directories:
    - node_modules/ # npm packages
    - .nyc_output/

node_js:
  - 'node'
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'

before_install:
  - npm install yarn -g
  - npm install codecov -g

install:
  - yarn --ignore-engines

stages:
  - test
  - compile

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: yarn coverage
      after_success:
        - codecov -f .nyc_output/*.json
    - stage: compile
      script: yarn build
      on:
        node: "12"
    - stage: deploy
      if: tag IS present
      provider: npm
      email: "$NPM_EMAIL",
      api_key："$NPM_TOKEN"
      skip_cleanup: true
      on:
        node: "12"
        tags: true


